// utils/colors.ts
export const colorMap: Record<string, string> = {

  Amarillo:"bg-yellow-400",
  Azul: "bg-blue-600",
  Azul_claro: "bg-blue-300",
  Azul_oscuro:"bg-blue-900",
  Blanco: "bg-white border border-gray-300", 
  Blanco_perlado:"bg-gray-300",
  Bronce:"bg-neutral-800",
  Beige:"bg-stone-700",
  Cafe_claro: "bg-orange-200",
  cafe:"bg-zinc-900",
  Cafe: "bg-amber-950",
  Celeste:"bg-blue-500",
  Gris: "bg-gray-500",
  Guindo: "bg-pink-950",
  Negro: "bg-black",
  Naranja: "bg-orange-500",
  Morado:"bg-indigo-400", 
  Plata: "bg-gray-300", 
  Plomo: "bg-gray-500",
  Rojo:"bg-red-600",
  Rojo_scarlet:"bg-pink-950",
  Turquesa:"bg-blue-800",
  Verde: "bg-emerald-700",
  Verde_oscuro: "bg-green-800",
  Verde_limon: "bg-lime-400",
  Verde_metal:"bg-teal-800",
  Verde_claro:"bg-green-400",
  
};
